import MightDeckMain from "./MightDeckMain";

const DECKDETAILS = [
  {
    deckID: "owhite",
    deckColour: "White",
    deckType: "Oathsworn",
    deck: [
      {
        cardID: "owhite0",
        value: 0,
        description: "miss",
        isCrit: false,
        isMiss: true,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
      {
        cardID: "owhite1",
        value: 0,
        description: "miss",
        isCrit: false,
        isMiss: true,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
      {
        cardID: "owhite2",
        value: 0,
        description: "miss",
        isCrit: false,
        isMiss: true,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
      {
        cardID: "owhite3",
        value: 0,
        description: "miss",
        isCrit: false,
        isMiss: true,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
      {
        cardID: "owhite4",
        value: 0,
        description: "miss",
        isCrit: false,
        isMiss: true,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
      {
        cardID: "owhite5",
        value: 0,
        description: "miss",
        isCrit: false,
        isMiss: true,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
      {
        cardID: "owhite6",
        value: 1,
        description: "hit",
        isCrit: false,
        isMiss: false,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
      {
        cardID: "owhite7",
        value: 1,
        description: "hit",
        isCrit: false,
        isMiss: false,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
      {
        cardID: "owhite8",
        value: 1,
        description: "hit",
        isCrit: false,
        isMiss: false,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
      {
        cardID: "owhite9",
        value: 1,
        description: "hit",
        isCrit: false,
        isMiss: false,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
      {
        cardID: "owhite10",
        value: 1,
        description: "hit",
        isCrit: false,
        isMiss: false,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
      {
        cardID: "owhite11",
        value: 1,
        description: "hit",
        isCrit: false,
        isMiss: false,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
      {
        cardID: "owhite12",
        value: 2,
        description: "hit",
        isCrit: false,
        isMiss: false,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
      {
        cardID: "owhite13",
        value: 2,
        description: "hit",
        isCrit: false,
        isMiss: false,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
      {
        cardID: "owhite14",
        value: 2,
        description: "hit",
        isCrit: false,
        isMiss: false,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
      {
        cardID: "owhite15",
        value: 2,
        description: "hit",
        isCrit: true,
        isMiss: false,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
      {
        cardID: "owhite16",
        value: 2,
        description: "hit",
        isCrit: true,
        isMiss: false,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
      {
        cardID: "owhite17",
        value: 2,
        description: "hit",
        isCrit: true,
        isMiss: false,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
    ],
  },
  {
    deckID: "oyellow",
    deckColour: "Yellow",
    deckType: "Oathsworn",
    deck: [
      {
        cardID: "oyellow0",
        value: 0,
        description: "miss",
        isCrit: false,
        isMiss: true,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
      {
        cardID: "oyellow1",
        value: 0,
        description: "miss",
        isCrit: false,
        isMiss: true,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
      {
        cardID: "oyellow2",
        value: 0,
        description: "miss",
        isCrit: false,
        isMiss: true,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
      {
        cardID: "oyellow3",
        value: 0,
        description: "miss",
        isCrit: false,
        isMiss: true,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
      {
        cardID: "oyellow4",
        value: 0,
        description: "miss",
        isCrit: false,
        isMiss: true,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
      {
        cardID: "oyellow5",
        value: 0,
        description: "miss",
        isCrit: false,
        isMiss: true,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
      {
        cardID: "oyellow6",
        value: 1,
        description: "hit",
        isCrit: false,
        isMiss: false,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
      {
        cardID: "oyellow7",
        value: 1,
        description: "hit",
        isCrit: false,
        isMiss: false,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
      {
        cardID: "oyellow8",
        value: 1,
        description: "hit",
        isCrit: false,
        isMiss: false,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
      {
        cardID: "oyellow9",
        value: 2,
        description: "hit",
        isCrit: false,
        isMiss: false,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
      {
        cardID: "oyellow10",
        value: 2,
        description: "hit",
        isCrit: false,
        isMiss: false,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
      {
        cardID: "oyellow11",
        value: 2,
        description: "hit",
        isCrit: false,
        isMiss: false,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
      {
        cardID: "oyellow12",
        value: 3,
        description: "hit",
        isCrit: false,
        isMiss: false,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
      {
        cardID: "oyellow13",
        value: 3,
        description: "hit",
        isCrit: false,
        isMiss: false,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
      {
        cardID: "oyellow14",
        value: 3,
        description: "hit",
        isCrit: false,
        isMiss: false,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
      {
        cardID: "oyellow15",
        value: 3,
        description: "hit",
        isCrit: true,
        isMiss: false,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
      {
        cardID: "oyellow16",
        value: 3,
        description: "hit",
        isCrit: true,
        isMiss: false,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
      {
        cardID: "oyellow17",
        value: 3,
        description: "hit",
        isCrit: true,
        isMiss: false,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
    ],
  },
  {
    deckID: "ored",
    deckColour: "Red",
    deckType: "Oathsworn",
    deck: [
      {
        cardID: "ored0",
        value: 0,
        description: "miss",
        isCrit: false,
        isMiss: true,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
      {
        cardID: "ored1",
        value: 0,
        description: "miss",
        isCrit: false,
        isMiss: true,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
      {
        cardID: "ored2",
        value: 0,
        description: "miss",
        isCrit: false,
        isMiss: true,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
      {
        cardID: "ored3",
        value: 0,
        description: "miss",
        isCrit: false,
        isMiss: true,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
      {
        cardID: "ored4",
        value: 0,
        description: "miss",
        isCrit: false,
        isMiss: true,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
      {
        cardID: "ored5",
        value: 0,
        description: "miss",
        isCrit: false,
        isMiss: true,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
      {
        cardID: "ored6",
        value: 2,
        description: "hit",
        isCrit: false,
        isMiss: false,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
      {
        cardID: "ored7",
        value: 2,
        description: "hit",
        isCrit: false,
        isMiss: false,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
      {
        cardID: "ored8",
        value: 2,
        description: "hit",
        isCrit: false,
        isMiss: false,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
      {
        cardID: "ored9",
        value: 3,
        description: "hit",
        isCrit: false,
        isMiss: false,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
      {
        cardID: "ored10",
        value: 3,
        description: "hit",
        isCrit: false,
        isMiss: false,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
      {
        cardID: "ored11",
        value: 3,
        description: "hit",
        isCrit: false,
        isMiss: false,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
      {
        cardID: "ored12",
        value: 3,
        description: "hit",
        isCrit: false,
        isMiss: false,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
      {
        cardID: "ored13",
        value: 3,
        description: "hit",
        isCrit: false,
        isMiss: false,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
      {
        cardID: "ored14",
        value: 3,
        description: "hit",
        isCrit: false,
        isMiss: false,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
      {
        cardID: "ored15",
        value: 4,
        description: "hit",
        isCrit: true,
        isMiss: false,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
      {
        cardID: "ored16",
        value: 4,
        description: "hit",
        isCrit: true,
        isMiss: false,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
      {
        cardID: "ored17",
        value: 4,
        description: "hit",
        isCrit: true,
        isMiss: false,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
    ],
  },
  {
    deckID: "oblack",
    deckColour: "Black",
    deckType: "Oathsworn",
    deck: [
      {
        cardID: "oblack0",
        value: 0,
        description: "miss",
        isCrit: false,
        isMiss: true,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
      {
        cardID: "oblack1",
        value: 0,
        description: "miss",
        isCrit: false,
        isMiss: true,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
      {
        cardID: "oblack2",
        value: 0,
        description: "miss",
        isCrit: false,
        isMiss: true,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
      {
        cardID: "oblack3",
        value: 0,
        description: "miss",
        isCrit: false,
        isMiss: true,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
      {
        cardID: "oblack4",
        value: 0,
        description: "miss",
        isCrit: false,
        isMiss: true,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
      {
        cardID: "oblack5",
        value: 0,
        description: "miss",
        isCrit: false,
        isMiss: true,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
      {
        cardID: "oblack6",
        value: 3,
        description: "hit",
        isCrit: false,
        isMiss: false,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
      {
        cardID: "oblack7",
        value: 3,
        description: "hit",
        isCrit: false,
        isMiss: false,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
      {
        cardID: "oblack8",
        value: 3,
        description: "hit",
        isCrit: false,
        isMiss: false,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
      {
        cardID: "oblack9",
        value: 3,
        description: "hit",
        isCrit: false,
        isMiss: false,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
      {
        cardID: "oblack10",
        value: 3,
        description: "hit",
        isCrit: false,
        isMiss: false,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
      {
        cardID: "oblack11",
        value: 3,
        description: "hit",
        isCrit: false,
        isMiss: false,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
      {
        cardID: "oblack12",
        value: 4,
        description: "hit",
        isCrit: false,
        isMiss: false,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
      {
        cardID: "oblack13",
        value: 4,
        description: "hit",
        isCrit: false,
        isMiss: false,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
      {
        cardID: "oblack14",
        value: 4,
        description: "hit",
        isCrit: false,
        isMiss: false,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
      {
        cardID: "oblack15",
        value: 5,
        description: "hit",
        isCrit: true,
        isMiss: false,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
      {
        cardID: "oblack16",
        value: 5,
        description: "hit",
        isCrit: true,
        isMiss: false,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
      {
        cardID: "oblack17",
        value: 5,
        description: "hit",
        isCrit: true,
        isMiss: false,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
    ],
  },
  {
    deckID: "ewhite",
    deckColour: "White",
    deckType: "Enemy",
    deck: [
      {
        cardID: "ewhite0",
        value: 0,
        description: "miss",
        isCrit: false,
        isMiss: true,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
      {
        cardID: "ewhite1",
        value: 0,
        description: "miss",
        isCrit: false,
        isMiss: true,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
      {
        cardID: "ewhite2",
        value: 0,
        description: "miss",
        isCrit: false,
        isMiss: true,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
      {
        cardID: "ewhite3",
        value: 0,
        description: "miss",
        isCrit: false,
        isMiss: true,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
      {
        cardID: "ewhite4",
        value: 0,
        description: "miss",
        isCrit: false,
        isMiss: true,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
      {
        cardID: "ewhite5",
        value: 0,
        description: "miss",
        isCrit: false,
        isMiss: true,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
      {
        cardID: "ewhite6",
        value: 1,
        description: "hit",
        isCrit: false,
        isMiss: false,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
      {
        cardID: "ewhite7",
        value: 1,
        description: "hit",
        isCrit: false,
        isMiss: false,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
      {
        cardID: "ewhite8",
        value: 1,
        description: "hit",
        isCrit: false,
        isMiss: false,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
      {
        cardID: "ewhite9",
        value: 1,
        description: "hit",
        isCrit: false,
        isMiss: false,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
      {
        cardID: "ewhite10",
        value: 1,
        description: "hit",
        isCrit: false,
        isMiss: false,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
      {
        cardID: "ewhite11",
        value: 1,
        description: "hit",
        isCrit: false,
        isMiss: false,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
      {
        cardID: "ewhite12",
        value: 2,
        description: "hit",
        isCrit: false,
        isMiss: false,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
      {
        cardID: "ewhite13",
        value: 2,
        description: "hit",
        isCrit: false,
        isMiss: false,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
      {
        cardID: "ewhite14",
        value: 2,
        description: "hit",
        isCrit: false,
        isMiss: false,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
      {
        cardID: "ewhite15",
        value: 2,
        description: "hit",
        isCrit: true,
        isMiss: false,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
      {
        cardID: "ewhite16",
        value: 2,
        description: "hit",
        isCrit: true,
        isMiss: false,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
      {
        cardID: "ewhite17",
        value: 2,
        description: "hit",
        isCrit: true,
        isMiss: false,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
    ],
  },
  {
    deckID: "eyellow",
    deckColour: "Yellow",
    deckType: "Enemy",
    deck: [
      {
        cardID: "eyellow0",
        value: 0,
        description: "miss",
        isCrit: false,
        isMiss: true,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
      {
        cardID: "eyellow1",
        value: 0,
        description: "miss",
        isCrit: false,
        isMiss: true,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
      {
        cardID: "eyellow2",
        value: 0,
        description: "miss",
        isCrit: false,
        isMiss: true,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
      {
        cardID: "eyellow3",
        value: 0,
        description: "miss",
        isCrit: false,
        isMiss: true,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
      {
        cardID: "eyellow4",
        value: 0,
        description: "miss",
        isCrit: false,
        isMiss: true,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
      {
        cardID: "eyellow5",
        value: 0,
        description: "miss",
        isCrit: false,
        isMiss: true,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
      {
        cardID: "eyellow6",
        value: 1,
        description: "hit",
        isCrit: false,
        isMiss: false,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
      {
        cardID: "eyellow7",
        value: 1,
        description: "hit",
        isCrit: false,
        isMiss: false,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
      {
        cardID: "eyellow8",
        value: 1,
        description: "hit",
        isCrit: false,
        isMiss: false,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
      {
        cardID: "eyellow9",
        value: 2,
        description: "hit",
        isCrit: false,
        isMiss: false,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
      {
        cardID: "eyellow10",
        value: 2,
        description: "hit",
        isCrit: false,
        isMiss: false,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
      {
        cardID: "eyellow11",
        value: 2,
        description: "hit",
        isCrit: false,
        isMiss: false,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
      {
        cardID: "eyellow12",
        value: 3,
        description: "hit",
        isCrit: false,
        isMiss: false,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
      {
        cardID: "eyellow13",
        value: 3,
        description: "hit",
        isCrit: false,
        isMiss: false,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
      {
        cardID: "eyellow14",
        value: 3,
        description: "hit",
        isCrit: false,
        isMiss: false,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
      {
        cardID: "eyellow15",
        value: 3,
        description: "hit",
        isCrit: true,
        isMiss: false,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
      {
        cardID: "eyellow16",
        value: 3,
        description: "hit",
        isCrit: true,
        isMiss: false,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
      {
        cardID: "eyellow17",
        value: 3,
        description: "hit",
        isCrit: true,
        isMiss: false,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
    ],
  },
  {
    deckID: "ered",
    deckColour: "Red",
    deckType: "Enemy",
    deck: [
      {
        cardID: "ered0",
        value: 0,
        description: "miss",
        isCrit: false,
        isMiss: true,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
      {
        cardID: "ered1",
        value: 0,
        description: "miss",
        isCrit: false,
        isMiss: true,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
      {
        cardID: "ered2",
        value: 0,
        description: "miss",
        isCrit: false,
        isMiss: true,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
      {
        cardID: "ered3",
        value: 0,
        description: "miss",
        isCrit: false,
        isMiss: true,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
      {
        cardID: "ered4",
        value: 0,
        description: "miss",
        isCrit: false,
        isMiss: true,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
      {
        cardID: "ered5",
        value: 0,
        description: "miss",
        isCrit: false,
        isMiss: true,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
      {
        cardID: "ered6",
        value: 2,
        description: "hit",
        isCrit: false,
        isMiss: false,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
      {
        cardID: "ered7",
        value: 2,
        description: "hit",
        isCrit: false,
        isMiss: false,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
      {
        cardID: "ered8",
        value: 2,
        description: "hit",
        isCrit: false,
        isMiss: false,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
      {
        cardID: "ered9",
        value: 3,
        description: "hit",
        isCrit: false,
        isMiss: false,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
      {
        cardID: "ered10",
        value: 3,
        description: "hit",
        isCrit: false,
        isMiss: false,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
      {
        cardID: "ered11",
        value: 3,
        description: "hit",
        isCrit: false,
        isMiss: false,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
      {
        cardID: "ered12",
        value: 3,
        description: "hit",
        isCrit: false,
        isMiss: false,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
      {
        cardID: "ered13",
        value: 3,
        description: "hit",
        isCrit: false,
        isMiss: false,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
      {
        cardID: "ered14",
        value: 3,
        description: "hit",
        isCrit: false,
        isMiss: false,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
      {
        cardID: "ered15",
        value: 4,
        description: "hit",
        isCrit: true,
        isMiss: false,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
      {
        cardID: "ered16",
        value: 4,
        description: "hit",
        isCrit: true,
        isMiss: false,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
      {
        cardID: "ered17",
        value: 4,
        description: "hit",
        isCrit: true,
        isMiss: false,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
    ],
  },
  {
    deckID: "eblack",
    deckColour: "Black",
    deckType: "Enemy",
    deck: [
      {
        cardID: "eblack0",
        value: 0,
        description: "miss",
        isCrit: false,
        isMiss: true,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
      {
        cardID: "eblack1",
        value: 0,
        description: "miss",
        isCrit: false,
        isMiss: true,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
      {
        cardID: "eblack2",
        value: 0,
        description: "miss",
        isCrit: false,
        isMiss: true,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
      {
        cardID: "eblack3",
        value: 0,
        description: "miss",
        isCrit: false,
        isMiss: true,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
      {
        cardID: "eblack4",
        value: 0,
        description: "miss",
        isCrit: false,
        isMiss: true,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
      {
        cardID: "eblack5",
        value: 0,
        description: "miss",
        isCrit: false,
        isMiss: true,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
      {
        cardID: "eblack6",
        value: 3,
        description: "hit",
        isCrit: false,
        isMiss: false,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
      {
        cardID: "eblack7",
        value: 3,
        description: "hit",
        isCrit: false,
        isMiss: false,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
      {
        cardID: "eblack8",
        value: 3,
        description: "hit",
        isCrit: false,
        isMiss: false,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
      {
        cardID: "eblack9",
        value: 3,
        description: "hit",
        isCrit: false,
        isMiss: false,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
      {
        cardID: "eblack10",
        value: 3,
        description: "hit",
        isCrit: false,
        isMiss: false,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
      {
        cardID: "eblack11",
        value: 3,
        description: "hit",
        isCrit: false,
        isMiss: false,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
      {
        cardID: "eblack12",
        value: 4,
        description: "hit",
        isCrit: false,
        isMiss: false,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
      {
        cardID: "eblack13",
        value: 4,
        description: "hit",
        isCrit: false,
        isMiss: false,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
      {
        cardID: "eblack14",
        value: 4,
        description: "hit",
        isCrit: false,
        isMiss: false,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
      {
        cardID: "eblack15",
        value: 5,
        description: "hit",
        isCrit: true,
        isMiss: false,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
      {
        cardID: "eblack16",
        value: 5,
        description: "hit",
        isCrit: true,
        isMiss: false,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
      {
        cardID: "eblack17",
        value: 5,
        description: "hit",
        isCrit: true,
        isMiss: false,
        isDealt: false,
        isActive: false,
        isSelected: false,
      },
    ],
  },
];

export default function DeckDetails() {
  return <MightDeckMain DECKS={DECKDETAILS} />;
}
